### ISSUE TITLE
Validation design ?

### ISSUE THREAD

**Issue by lcrmorin** [signaux-faibles/predictsignauxfaibles#28]
I was re-reading the validation documentation and the validation set building code and tried to picture the whole thing. I came up with that: 

![image](https://user-images.githubusercontent.com/4086709/109342255-df698380-786b-11eb-8c87-cca561759d6a.png)

Am I understanding the validation design correctly ?
If yes, can I just add the picture to the documentation ?

**Comment by slebastard** [comment]
- I believe your drawing is correct in that it corresponds to the behaviour of model_selection.make_sf_test_validate_splits(). This looks like the reverse of a standard k-fold cross-validation: instead of training in a leave-one-out fashion (training on k-1 splits and validating on the remaining one), we train on one split and validate on the k-1 remainder. @JazzyPierrot is this the intended behaviour? Was this intended to cope with macroeconomic fluctuations? I could not figure it out from the documentation at https://github.com/signaux-faibles/documentation/blob/master/algorithme-evaluation.md#%C3%A9valuation-du-mod%C3%A8le
- Indeed I don't think we build embargo sets

**Comment by vviers** [comment]
Does #32 fix it ?
